# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33e8b3b09906bf71c28bd201319578d1ee84e955872a98a622d421867ccd9078d524ec91f0372bdb5e0add645f046fd39c3520a21078751e95f115949fff06a0

test:
  secret_key_base: d5f633c7dc78c70d594a9d1d97149fcd7dcb85c984447d1f6ebba8b430787740ae9b215752072e887e083cab67ed022db6517b2e47529b8fe3182bd35cbc0c75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
